/**
 * AUSF API
 * AUSF UE Authentication Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * AuthResult.h
 *
 *
 */

#ifndef AuthResult_H_
#define AuthResult_H_

#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
///
/// </summary>
class AuthResult {
public:
  AuthResult();
  virtual ~AuthResult();

  void validate();

  /////////////////////////////////////////////
  /// AuthResult members

  friend void to_json(nlohmann::json &j, const AuthResult &o);
  friend void from_json(const nlohmann::json &j, AuthResult &o);

protected:
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* AuthResult_H_ */
