/**
 * AUSF API
 * AUSF UE Authentication Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * ConfirmationDataResponse.h
 *
 *
 */

#ifndef ConfirmationDataResponse_H_
#define ConfirmationDataResponse_H_

#include "AuthResult.h"
#include <nlohmann/json.hpp>
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
///
/// </summary>
class ConfirmationDataResponse {
public:
  ConfirmationDataResponse();
  virtual ~ConfirmationDataResponse();

  void validate();

  /////////////////////////////////////////////
  /// ConfirmationDataResponse members

  /// <summary>
  ///
  /// </summary>
  AuthResult getAuthResult() const;
  void setAuthResult(AuthResult const &value);
  /// <summary>
  ///
  /// </summary>
  std::string getSupi() const;
  void setSupi(std::string const &value);
  bool supiIsSet() const;
  void unsetSupi();
  /// <summary>
  ///
  /// </summary>
  std::string getKseaf() const;
  void setKseaf(std::string const &value);
  bool kseafIsSet() const;
  void unsetKseaf();

  friend void to_json(nlohmann::json &j, const ConfirmationDataResponse &o);
  friend void from_json(const nlohmann::json &j, ConfirmationDataResponse &o);

protected:
  AuthResult m_AuthResult;

  std::string m_Supi;
  bool m_SupiIsSet;
  std::string m_Kseaf;
  bool m_KseafIsSet;
};

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org

#endif /* ConfirmationDataResponse_H_ */
