/**
 * AUSF API
 * AUSF UE Authentication Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "TraceDepth.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

TraceDepth::TraceDepth() {}

TraceDepth::~TraceDepth() {}

void TraceDepth::validate() {
  // TODO: implement validation
}

void to_json(nlohmann::json &j, const TraceDepth &o) { j = nlohmann::json(); }

void from_json(const nlohmann::json &j, TraceDepth &o) {}

} // namespace model
} // namespace server
} // namespace openapitools
} // namespace org
