/**
* AUSF API
* AUSF UE Authentication Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.1.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* AuthenticationResultDeletionApiImpl.h
*
* 
*/

#ifndef AUTHENTICATION_RESULT_DELETION_API_IMPL_H_
#define AUTHENTICATION_RESULT_DELETION_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <AuthenticationResultDeletionApi.h>

#include <pistache/optional.h>

#include "ProblemDetails.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class AuthenticationResultDeletionApiImpl : public org::openapitools::server::api::AuthenticationResultDeletionApi {
public:
    AuthenticationResultDeletionApiImpl(std::shared_ptr<Pistache::Rest::Router>);
    ~AuthenticationResultDeletionApiImpl() {}

    void delete5g_aka_authentication_result(const std::string &authCtxId, Pistache::Http::ResponseWriter &response);
    void delete_eap_authentication_result(const std::string &authCtxId, Pistache::Http::ResponseWriter &response);

};

}
}
}
}



#endif