/**
 * AUSF API
 * AUSF UE Authentication Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "AuthenticationResultDeletionApiImpl.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

AuthenticationResultDeletionApiImpl::AuthenticationResultDeletionApiImpl(
    std::shared_ptr<Pistache::Rest::Router> rtr, ausf_app* ausf_app_inst,
    std::string address)
    : AuthenticationResultDeletionApi(rtr),
      m_ausf_app(ausf_app_inst),
      m_address(address) {}

void AuthenticationResultDeletionApiImpl::delete5g_aka_authentication_result(
    const std::string& authCtxId, Pistache::Http::ResponseWriter& response) {
  response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}
void AuthenticationResultDeletionApiImpl::delete_eap_authentication_result(
    const std::string& authCtxId, Pistache::Http::ResponseWriter& response) {
  response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}

}  // namespace api
}  // namespace server
}  // namespace openapitools
}  // namespace org
