/**
 * AUSF API
 * AUSF UE Authentication Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */

#include "AuthenticationResultDeletionApiImpl.h"
#include "logger.hpp"

namespace oai {
namespace ausf_server {
namespace api {

using namespace oai::model::ausf;

AuthenticationResultDeletionApiImpl::AuthenticationResultDeletionApiImpl(
    std::shared_ptr<Pistache::Rest::Router> rtr, ausf_app* ausf_app_inst,
    std::string address)
    : AuthenticationResultDeletionApi(rtr),
      m_ausf_app(ausf_app_inst),
      m_address(address) {}

void AuthenticationResultDeletionApiImpl::delete5g_aka_authentication_result(
    const std::string& authCtxId, Pistache::Http::ResponseWriter& response) {
  Logger::ausf_server().info("delete5g_aka_authentication_result");
  response.send(
      Pistache::Http::Code::Not_Implemented,
      "delete5g_aka_authentication_result API has not been implemented yet!\n");
}
void AuthenticationResultDeletionApiImpl::delete_eap_authentication_result(
    const std::string& authCtxId, Pistache::Http::ResponseWriter& response) {
  Logger::ausf_server().info("delete_eap_authentication_result");
  response.send(
      Pistache::Http::Code::Not_Implemented,
      "delete_eap_authentication_result API has not been implemented yet!\n");
}

}  // namespace api
}  // namespace ausf_server
}  // namespace oai
