/**
 * AUSF API
 * AUSF UE Authentication Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */

/*
 * AuthenticationResultDeletionApiImpl.h
 *
 *
 */

#ifndef AUTHENTICATION_RESULT_DELETION_API_IMPL_H_
#define AUTHENTICATION_RESULT_DELETION_API_IMPL_H_

#include <memory>
#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>

#include <AuthenticationResultDeletionApi.h>

#include <pistache/optional.h>

#include "ProblemDetails.h"
#include "ausf_app.hpp"
#include <string>

namespace oai {
namespace ausf_server {
namespace api {

using namespace oai::ausf::app;
using namespace oai::model::ausf;

class AuthenticationResultDeletionApiImpl
    : public oai::ausf_server::api::AuthenticationResultDeletionApi {
 public:
  AuthenticationResultDeletionApiImpl(
      std::shared_ptr<Pistache::Rest::Router>, ausf_app* ausf_app_inst,
      std::string address);
  ~AuthenticationResultDeletionApiImpl() {}

  void delete5g_aka_authentication_result(
      const std::string& authCtxId, Pistache::Http::ResponseWriter& response);
  void delete_eap_authentication_result(
      const std::string& authCtxId, Pistache::Http::ResponseWriter& response);

 private:
  ausf_app* m_ausf_app;
  std::string m_address;
};

}  // namespace api
}  // namespace ausf_server
}  // namespace oai

#endif
