## amf configuration file
AUSF = 
{
  INSTANCE_ID = 10; #10
  PID_DIRECTORY = "/var/run";
######################################################################## NG SETUP RESPONSE IEs ############################################################
  AUSF_NAME = "bupt-ausf";
#   GUAMI:{MCC = "110"; MNC = "11"; RegionID = "128"; AMFSetID = "4"; AMFPointer = "1"}
#   SERVED_GUAMI_LIST = (
#    {MCC = "110"; MNC = "11"; RegionID = "10"; AMFSetID = "1"; AMFPointer = "0"}, #48bits <MCC><MNC><RegionID><AMFSetID><AMFPointer>
#    {MCC = "110"; MNC = "11"; RegionID = "10"; AMFSetID = "1"; AMFPointer = "1"} #48bits <MCC><MNC><RegionID><AMFSetID><AMFPointer>
#   );
#   RELATIVE_CAPACITY = 30;

#   PLMN_SUPPORT_LIST = (
#     {MCC = "110"; MNC = "11"; TAC = 100; 
#      SLICE_SUPPORT_LIST = (
#       {SST = "1"; SD = "none"}, 
#       {SST = "1"; SD = "12"}
#      )
#     }
#   );
##################################################################### clause 9.2.6.2, 3gpp ts38.413 ####################################################
  #STATISTICS_TIMER_INTERVAL = 20; #second

  INTERFACES:{
    SBI_AUSF:{
        INTERFACE_NAME = "ens33";               #interface for providing ausf service
        IPV4_ADDRESS   = "192.168.2.101/24";   #"192.168.61.141/24";   #address for intercafe (cidr)
        PORT           = 8383;                  #ausf service port 
        PPID           = 60;
    };
    NUDM:{
        INTERFACE_NAME = "ens32";               #interface for providing udm service
        IPV4_ADDRESS   = "192.168.2.35/24";   #address for intercafe (cidr)
        PORT           = 8181;                  #udm service port 
        #PPID           = 60;
    };
    NAMF:{
        INTERFACE_NAME = "ens33";               #interface for request for amf service
        IPV4_ADDRESS   = "192.168.2.101/24";   #amf address (cidr)
        PORT           = 8383;                  #amf port
    };
    # NUDR:{
    #     INTERFACE_NAME = "ens33";               #interface for request for udr service
    #     IPV4_ADDRESS   = "192.168.21.133/24";  #udr address (cidr)
    #     PORT           = 8080;                  #udr port
    #     VERSION        = "v2"; 
    # };
  };

#   CORE_CONFIGURATION:{
#     EMERGENCY_SUPPORT = "false";
#   };

#   AUTHENTICATION:{
#     MYSQL_server = "127.0.0.1";
#     MYSQL_user   = "bupt";  # Database server login
#     MYSQL_pass   = "linux";  # Database server password
#     MYSQL_db     = "OAI_DB";
#     OPERATOR_key = "1006020f0a478bf6b699f15c062e42b3"; # op
#     RANDOM = "true";
#   };

};


