## amf configuration file
AUSF = 
{
  INSTANCE_ID = 10; #10
  PID_DIRECTORY = "/var/run";
######################################################################## NG SETUP RESPONSE IEs ############################################################
  AUSF_NAME = "OAI-AUSF";

##################################################################### clause 9.2.6.2, 3gpp ts38.413 ####################################################
  #STATISTICS_TIMER_INTERVAL = 20; #second

  INTERFACES:{
    SBI_AUSF:{
        INTERFACE_NAME = "wlo1";               #interface for providing ausf service
        IPV4_ADDRESS   = "192.168.1.23/24";   #"192.168.61.141/24";   #address for intercafe (cidr)
        PORT           = 8383;                  #ausf service port 
        PPID           = 60;
    };
    NUDM:{
        INTERFACE_NAME = "wlo1";               #interface for providing udm service
        IPV4_ADDRESS   = "192.168.1.23/24";   #address for intercafe (cidr)
        PORT           = 8181;                  #udm service port 
        #PPID           = 60;
    };
    NAMF:{
        INTERFACE_NAME = "wlo1";               #interface for request for amf service
        IPV4_ADDRESS   = "192.168.1.23/24";   #amf address (cidr)
        PORT           = 8383;                  #amf port
    };
  };

};


