## AUSF configuration file
AUSF =
{
  INSTANCE_ID = @INSTANCE_ID@;
  PID_DIRECTORY = "@PID_DIR@";
  AUSF_NAME = "@AUSF_NAME@";

  INTERFACES:{
    # AUSF binded interface for SBI interface (e.g., communication with AMF, UDM)
    SBI:{
        INTERFACE_NAME = "@SBI_IF_NAME@";  # YOUR NETWORK CONFIG HERE
        IPV4_ADDRESS   = "read";
        PORT           = @SBI_PORT@;       # YOUR NETWORK CONFIG HERE (default: 80)
        PPID           = 60;
    };
  };

  # UDM Information
  UDM:{
     IPV4_ADDRESS   = "@UDM_IP_ADDRESS@";  # YOUR NETWORK CONFIG HERE
     PORT           = @UDM_PORT@;          # YOUR NETWORK CONFIG HERE  (default: 80)
     API_VERSION    = "@UDM_VERSION_NB@";  # YOUR AMF API VERSION FOR UDM CONFIG HERE
    };

  # AMF Information
  AMF:{
     IPV4_ADDRESS   = "@AMF_IP_ADDRESS@";  # YOUR NETWORK CONFIG HERE  (default: 80)
     PORT           = @AMF_PORT@;          # YOUR NETWORK CONFIG HERE  (default: 80)
     API_VERSION    = "@AMF_VERSION_NB@";  # YOUR AMF API VERSION FOR UDM CONFIG HERE
    };

};
