#/*
# * SPDX-License-Identifier: LicenseRef-CSSL-1.0
# */

#---------------------------------------------------------------------
#
# Dockerfile for the Open-Air-Interface AUSF service
#   Valid for UBI 9.x | RHEL 9.x
#
#---------------------------------------------------------------------

#---------------------------------------------------------------------
# BUILDER IMAGE
#---------------------------------------------------------------------

FROM registry.redhat.io/ubi9/ubi:latest AS oai-ausf-builder

ARG EPEL_URL
ENV EPEL_URL=${EPEL_URL}

ENV IS_DOCKERFILE=1

# Copy the entitlements
COPY ./etc-pki-entitlement /etc/pki/entitlement

RUN rm -f /etc/rhsm-host && \
    subscription-manager repos --enable codeready-builder-for-rhel-9-x86_64-rpms && \
    dnf update -y --allowerasing --skip-broken --nobest && \
    # here just to display the current version
    cat /etc/os-release && \
    dnf install -y \
        psmisc \
        git \
        diffutils \
        libasan \
        wget \
        file && \
    echo "/usr/local/lib" > /etc/ld.so.conf.d/local-lib.conf && \
    echo "/usr/local/lib64" >> /etc/ld.so.conf.d/local-lib.conf

ARG YQ_VERSION=v4.47.1
RUN case $(uname -m) in \
        x86_64)  YQ_BIN="yq_linux_amd64" ;; \
        aarch64) YQ_BIN="yq_linux_arm64" ;; \
        *) echo "Unsupported arch"; exit 1 ;; \
    esac && \
    wget https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/${YQ_BIN} -O /usr/local/bin/yq && \
    chmod +x /usr/local/bin/yq

# Some GIT configuration command quite useful
RUN git config --global https.postBuffer 123289600 && \
    git config --global http.sslverify false

# Copying source code
WORKDIR /openair-ausf
COPY . /openair-ausf

# Installing and Building AUSF
WORKDIR /openair-ausf/build/scripts
RUN ./build_ausf --install-deps --force
RUN ./build_ausf --clean --Verbose --build-type Release --jobs && \
    ldd /openair-ausf/build/ausf/build/ausf && \
    mv /openair-ausf/build/ausf/build/ausf /openair-ausf/build/ausf/build/oai_ausf && \
    # Remove entitlements and Subscription Manager configs
    rm -rf /etc/pki/entitlement


#---------------------------------------------------------------------
# TARGET IMAGE
#---------------------------------------------------------------------
FROM registry.redhat.io/ubi9/ubi-minimal:latest as oai-ausf
ENV TZ=Europe/Paris
# We install some debug tools for the moment in addition of mandatory libraries

# Copy the entitlements
COPY ./etc-pki-entitlement /etc/pki/entitlement
# Copy the subscription manager configurations
COPY --from=oai-ausf-builder /etc/rhsm /etc/rhsm

# We install some debug tools for the moment in addition of mandatory libraries
RUN rm -f /etc/rhsm-host && \
    microdnf update -y && \
    microdnf install -y \
# Debug Tools that are not mandatory
      tzdata \
      procps-ng \
      psmisc \
      net-tools \
      iputils \
      tcpdump \
# Mandatory packages for the NF to run
#      libasan \
      libicu \
      boost \
      libevent \
      findutils && \
    microdnf clean all -y && \
    rm -rf /var/cache/yum /var/cache/dnf && \
    # Remove entitlements and Subscription Manager configs
    rm -rf /etc/pki/entitlement && \
    rm -rf /etc/rhsm

# Copying executable and generated libraries
WORKDIR /openair-ausf/bin
COPY --from=oai-ausf-builder \
    /openair-ausf/build/ausf/build/oai_ausf \
    /openair-ausf/scripts/healthcheck.sh \
    ./
COPY --from=oai-ausf-builder /usr/local/bin/yq /usr/bin/yq

COPY --from=oai-ausf-builder \
# Copying only the packages built from source
    /usr/local/lib64/libpistache.so.0 \
    /usr/local/lib/libnghttp2_asio.so \
    /usr/local/lib/libnghttp2_asio.so.1 \
    /usr/local/lib64/libspdlog.so \
    /usr/local/lib64/libfmt.so \
    /usr/local/lib64/libyaml-cpp.so.0.* \
    /usr/local/lib64/libcpr.so.1 \  
    /usr/lib64/

RUN ldconfig && \
    ldd /openair-ausf/bin/oai_ausf

WORKDIR /openair-ausf/etc
COPY --from=oai-ausf-builder \
    /openair-ausf/etc/config.yaml ./

WORKDIR /openair-ausf

# expose ports
EXPOSE 80/tcp
# healthcheck
HEALTHCHECK --interval=10s \
            --timeout=15s \
            --retries=6 \
    CMD /openair-ausf/bin/healthcheck.sh

CMD ["/openair-ausf/bin/oai_ausf", "-c" , "/openair-ausf/etc/config.yaml", "-o"]
